/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cubrid_sqlanalyzer_core_runner_QueryParser */

#ifndef _Included_com_cubrid_sqlanalyzer_core_runner_QueryParser
#define _Included_com_cubrid_sqlanalyzer_core_runner_QueryParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cubrid_sqlanalyzer_core_runner_QueryParser
 * Method:    validateSQLNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cubrid_sqlanalyzer_core_runner_QueryParser_validateSQLNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
