/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_cubrid_sqlanalyzer_core_runner_QueryParser.h"

#include <jni.h>
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#endif

#include "dbi.h"
/* Header for class com_cubrid_sqlanalyzer_core_runner_QueryParser */

/* GLOBAL STATE */
#define DB_CONNECTION_STATUS_NOT_CONNECTED 0
#define DB_CONNECTION_STATUS_CONNECTED     1
#define DB_CONNECTION_STATUS_RESET        -1

#define NO_ERROR   0
#define ER_FAILED -1

#ifdef _WIN32
#define DEFAULT_LIBRARY_PATH "C:/CUBRID/bin/cubridcs.dll"
#else
#define DEFAULT_LIBRARY_PATH_SUFFIX "/lib/libcubridcs.so.11.4"
#endif
#define DEFAULT_LANG_CHARSET "ko_KR.utf8"
#define DEFAULT_BUF_LENGTH   1024

enum er_exit_ask {
	ER_NEVER_EXIT = 0,
	ER_EXIT_ASK = 1,
	ER_EXIT_DONT_ASK = 2,
	ER_ABORT = 3,
	ER_EXIT_DEFAULT = ER_NEVER_EXIT
};

typedef struct error_buf {
	char *buf;
	int length;
} ERROR_BUF;

typedef int (*fn_er_init)(const char *msglog_filename, int exit_ask);
typedef int (*fn_er_errid)();
typedef const char * (*fn_er_msg)();
typedef DB_SESSION_ERROR * (*fn_db_get_errors)(DB_SESSION * session);
typedef DB_SESSION_ERROR * (*fn_db_get_next_error)(DB_SESSION_ERROR * errors,
		int *line, int *col);
typedef int (*fn_lang_init)(); /* lang_Initialized */
typedef int (*fn_lang_set_charset_lang)(const char *lang_charset); /* lang_Language_initialized */
typedef void (*fn_db_set_connect_status)(int status);
typedef DB_SESSION * (*fn_db_open_buffer)(char * query);
typedef void (*fn_db_close_session)(DB_SESSION * session);

#ifdef _WIN32
typedef HINSTANCE LIB_HANDLE;
#else
typedef void * LIB_HANDLE;
#endif

static fn_er_init cub_er_init = NULL;
static fn_er_errid cub_er_errid = NULL;
static fn_er_msg cub_er_msg = NULL;
static fn_db_get_errors cub_db_get_errors = NULL;
static fn_db_get_next_error cub_db_get_next_error = NULL;
static fn_lang_init cub_lang_init = NULL;
static fn_lang_set_charset_lang cub_lang_set_charset_lang = NULL;
static fn_db_set_connect_status cub_db_set_connect_status = NULL;
static fn_db_open_buffer cub_db_open_buffer = NULL;
static fn_db_close_session cub_db_close_session = NULL;

static int load(LIB_HANDLE *hDLL, const char * libraryPath);
static int init(const char *lang_charset);
static int set_error(char ** error_buf, const char *er_msg);
static char * jstring_to_char(JNIEnv *env, jstring j_str);
static jstring char_to_jstring(JNIEnv *env, const char *str);
#ifndef _WIN32
static void * load_symbol_with_fallback(LIB_HANDLE hDLL, const char *symbol,
		const char *fallback_symbol);
#endif

/*
 * Class:     com_cubrid_sqlanalyzer_core_runner_QueryParser
 * Method:    validateSQL
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cubrid_sqlanalyzer_core_runner_QueryParser_validateSQL(
		JNIEnv *env, jobject j_obj, jstring j_str) {
	LIB_HANDLE hDLL = NULL;
#ifndef _WIN32
	char libraryPath[PATH_MAX];
	const char *cubrid = NULL;
#endif
	char *query = NULL;
	DB_SESSION *session = NULL;
	DB_SESSION_ERROR *session_error = NULL;
	char *out_buf = NULL;
	int out_buf_len = 0;
	int out_buf_maxlen = 0;
	int has_error = 0;
	jstring result = NULL;

#ifdef _WIN32
	if (load(&hDLL, DEFAULT_LIBRARY_PATH) != NO_ERROR) {
		goto exit_on_error;
	}
#else
	cubrid = getenv("CUBRID");
	if (cubrid == NULL || cubrid[0] == '\0') {
		fprintf(stderr, "CUBRID environment variable is not set.\n");
		goto exit_on_error;
	}

	if (snprintf(libraryPath, sizeof(libraryPath), "%s%s", cubrid,
			DEFAULT_LIBRARY_PATH_SUFFIX) >= (int) sizeof(libraryPath)) {
		fprintf(stderr, "CUBRID library path is too long.\n");
		goto exit_on_error;
	}

	if (load(&hDLL, libraryPath) != NO_ERROR) {
		goto exit_on_error;
	}
#endif

	if (init(DEFAULT_LANG_CHARSET) != NO_ERROR) {
		goto exit_on_error;
	}

	query = jstring_to_char(env, j_str);
	if (query == NULL) {
		goto exit_on_error;
	}

	session = cub_db_open_buffer(query);
	if (session == NULL) {
		fprintf(stderr, "Failed to db_open_buffer().\n");
		fprintf(stderr, "%s\n", cub_er_msg());
		goto exit_on_error;
	}

	session_error = cub_db_get_errors(session);
	do {
		int line = 0, col = 0;
		int len = 0;
		int error = NO_ERROR;
		const char *er_msg = NULL;

		session_error = cub_db_get_next_error(session_error, &line, &col);

		error = cub_er_errid();
		if (error != NO_ERROR) {
			has_error = 1;

			er_msg = cub_er_msg();

			len = snprintf(NULL, 0, "In line %d, column %d,\n\nERROR(%d): %s\n",
					line, col, error, er_msg);

			if (out_buf == NULL) {
				out_buf = malloc(sizeof(char) * DEFAULT_BUF_LENGTH);
				if (out_buf == NULL) {
					fprintf(stderr, "Failed to allocate memory.\n");
					goto exit_on_error;
				}

				out_buf_len = 0;
				out_buf_maxlen = DEFAULT_BUF_LENGTH;

				snprintf(out_buf, len,
						"In line %d, column %d,\n\nERROR(%d): %s\n", line, col,
						error, er_msg);
				out_buf_len += len;
			} else {
				if (out_buf_len + len > out_buf_maxlen) {
					out_buf = realloc(out_buf,
							sizeof(char)
									* (out_buf_maxlen + DEFAULT_BUF_LENGTH));
					if (out_buf == NULL) {
						fprintf(stderr, "Failed to allocate memory.\n");
						goto exit_on_error;
					}

					out_buf_maxlen += DEFAULT_BUF_LENGTH;
				}

				snprintf(out_buf + out_buf_len - 1, len,
						"In line %d, column %d,\n\nERROR(%d): %s\n", line, col,
						error, er_msg);
				out_buf_len += len;
			}
		}
	} while (session_error != NULL);

	free(query);
	query = NULL;

	cub_db_close_session(session);
	session = NULL;

	if (hDLL != NULL) {
#ifdef _WIN32
		FreeLibrary(hDLL);
#else
		dlclose(hDLL);
#endif
		hDLL = NULL;
	}

	if (has_error) {
		result = char_to_jstring(env, out_buf);
	} else {
		result = char_to_jstring(env, "NO_ERROR");
	}

	exit_on_error:

	if (query != NULL) {
		free(query);
		query = NULL;
	}

	if (out_buf != NULL) {
		free(out_buf);
		out_buf = NULL;
		out_buf_len = 0;
		out_buf_maxlen = 0;
	}

	if (session != NULL) {
		cub_db_close_session(session);
		session = NULL;
	}

	if (hDLL != NULL) {
#ifdef _WIN32
		FreeLibrary(hDLL);
#else
		dlclose(hDLL);
#endif
		hDLL = NULL;
	}

	return result;
}

static int load(LIB_HANDLE *hDLL, const char * libraryPath) {
#ifdef _WIN32
	*hDLL = LoadLibrary(libraryPath);
	if (*hDLL == NULL) {
		fprintf(stderr, "Failed to LoadLibrary( %s ).\n", libraryPath);
		return ER_FAILED;
	}
#else
	*hDLL = dlopen(libraryPath, RTLD_NOW);
	if (*hDLL == NULL) {
		fprintf(stderr, "Failed to dlopen( %s ): %s\n", libraryPath, dlerror());
		return ER_FAILED;
	}
#endif

#ifdef _WIN32
	cub_er_init = (fn_er_init) GetProcAddress(*hDLL, "er_init");
#else
	cub_er_init = (fn_er_init) dlsym(*hDLL, "er_init");
#endif
	if (cub_er_init == NULL) {
		fprintf(stderr, "Failed to load symbol(er_init).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_er_errid = (fn_er_errid) GetProcAddress(*hDLL, "er_errid");
#else
	cub_er_errid = (fn_er_errid) dlsym(*hDLL, "er_errid");
#endif
	if (cub_er_errid == NULL) {
		fprintf(stderr, "Failed to load symbol(er_errid).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_er_msg = (fn_er_msg) GetProcAddress(*hDLL, "er_msg");
#else
	cub_er_msg = (fn_er_msg) dlsym(*hDLL, "er_msg");
#endif
	if (cub_er_msg == NULL) {
		fprintf(stderr, "Failed to load symbol(er_msg).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_db_get_errors = (fn_db_get_errors) GetProcAddress(*hDLL, "db_get_errors");
#else
	cub_db_get_errors = (fn_db_get_errors) dlsym(*hDLL, "db_get_errors");
#endif
	if (cub_db_get_errors == NULL) {
		fprintf(stderr, "Failed to load symbol(db_get_errors).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_db_get_next_error = (fn_db_get_next_error) GetProcAddress(*hDLL,
			"db_get_next_error");
#else
	cub_db_get_next_error = (fn_db_get_next_error) dlsym(*hDLL,
			"db_get_next_error");
#endif
	if (cub_db_get_next_error == NULL) {
		fprintf(stderr, "Failed to load symbol(db_get_next_error).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_lang_init = (fn_lang_init) GetProcAddress(*hDLL, "lang_init");
#else
	cub_lang_init = (fn_lang_init) dlsym(*hDLL, "lang_init");
#endif
	if (cub_lang_init == NULL) {
		fprintf(stderr, "Failed to load symbol(lang_init).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_lang_set_charset_lang = (fn_lang_set_charset_lang) GetProcAddress(*hDLL,
			"lang_set_charset_lang");
#else
	cub_lang_set_charset_lang = (fn_lang_set_charset_lang) dlsym(*hDLL,
			"lang_set_charset_lang");
#endif
	if (cub_lang_set_charset_lang == NULL) {
		fprintf(stderr, "Failed to load symbol(lang_set_charset_lang).\n");
		return ER_FAILED;
	}

	/* dumpbin -exports cubridcs.dll | findstr db_open_buffer_local */
#ifdef _WIN32
	cub_db_set_connect_status = (fn_db_set_connect_status) GetProcAddress(*hDLL,
			"db_set_connect_status");
#else
	cub_db_set_connect_status = (fn_db_set_connect_status) load_symbol_with_fallback(
			*hDLL, "db_set_connect_status", "_Z21db_set_connect_statusi");
#endif
	if (cub_db_set_connect_status == NULL) {
		fprintf(stderr, "Failed to load symbol(db_set_connect_status).\n");
	}

#ifdef _WIN32
	cub_db_open_buffer = (fn_db_open_buffer) GetProcAddress(*hDLL,
			"db_open_buffer");
#else
	cub_db_open_buffer = (fn_db_open_buffer) dlsym(*hDLL, "db_open_buffer");
#endif
	if (cub_db_open_buffer == NULL) {
		fprintf(stderr, "Failed to load symbol(db_open_buffer).\n");
		return ER_FAILED;
	}

#ifdef _WIN32
	cub_db_close_session = (fn_db_close_session) GetProcAddress(*hDLL,
			"db_close_session");
#else
	cub_db_close_session = (fn_db_close_session) dlsym(*hDLL, "db_close_session");
#endif
	if (cub_db_close_session == NULL) {
		fprintf(stderr, "Failed to load symbol(db_close_session).\n");
		return ER_FAILED;
	}

	return NO_ERROR;
}

static int init(const char *lang_charset) {
	if (cub_er_init(NULL, ER_NEVER_EXIT) != NO_ERROR) {
		fprintf(stderr, "Failed to initialize error manager.\n");
		return ER_FAILED;
	}

	if (cub_lang_init() != NO_ERROR) {
		fprintf(stderr, "Failed to initialize language module.\n");
		return ER_FAILED;
	}

	if (cub_lang_set_charset_lang(lang_charset) != NO_ERROR) {
		fprintf(stderr, "Failed to initialize language module.\n");
		return ER_FAILED;
	}

	if (cub_db_set_connect_status != NULL) {
		cub_db_set_connect_status(DB_CONNECTION_STATUS_CONNECTED);
	}

	return NO_ERROR;
}

#ifndef _WIN32
static void * load_symbol_with_fallback(LIB_HANDLE hDLL, const char *symbol,
		const char *fallback_symbol) {
	void *fn = dlsym(hDLL, symbol);

	if (fn == NULL && fallback_symbol != NULL) {
		fn = dlsym(hDLL, fallback_symbol);
	}

	return fn;
}
#endif

static char * jstring_to_char(JNIEnv *env, jstring j_str) {
	const char *str = NULL;
	char *buf = NULL;

	if (j_str == NULL) {
		return NULL;
	}

	str = (*env)->GetStringUTFChars(env, j_str, NULL);
	buf = strdup(str);
	(*env)->ReleaseStringUTFChars(env, j_str, str);

	return buf;
}

static jstring char_to_jstring(JNIEnv *env, const char *str) {
	if (str == NULL) {
		return NULL;
	}

	return (*env)->NewStringUTF(env, str);
}
